//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KateHelloWorld.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KateHelloWorldEntities : DbContext
    {
        public KateHelloWorldEntities()
            : base("name=KateHelloWorldEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<HelloCity> HelloCities { get; set; }
        public virtual DbSet<RateCity> RateCities { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
