//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KateHelloWorldHelperLib.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KateHelloWorldHelperLib.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name must be alphanumeric..
        /// </summary>
        internal static string ErrorAlphanumericDisplayName {
            get {
                return ResourceManager.GetString("ErrorAlphanumericDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greeting cannot be blank..
        /// </summary>
        internal static string ErrorBlankGreeting {
            get {
                return ResourceManager.GetString("ErrorBlankGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating cannot be blank..
        /// </summary>
        internal static string ErrorBlankRating {
            get {
                return ResourceManager.GetString("ErrorBlankRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name must be between 5 and 15 characters..
        /// </summary>
        internal static string ErrorDisplayNameConstraint {
            get {
                return ResourceManager.GetString("ErrorDisplayNameConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greeting contains invalid characters..
        /// </summary>
        internal static string ErrorGreetingInvalidChars {
            get {
                return ResourceManager.GetString("ErrorGreetingInvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greeting must be between 5 and 100 characters..
        /// </summary>
        internal static string ErrorGreetingLength {
            get {
                return ResourceManager.GetString("ErrorGreetingLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CityId {0} is not a valid Guid..
        /// </summary>
        internal static string ErrorInvalidCityId {
            get {
                return ResourceManager.GetString("ErrorInvalidCityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId {0} is not a valid Guid..
        /// </summary>
        internal static string ErrorInvalidUserId {
            get {
                return ResourceManager.GetString("ErrorInvalidUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating must be a number..
        /// </summary>
        internal static string ErrorRatingNumberic {
            get {
                return ResourceManager.GetString("ErrorRatingNumberic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating must be between 1 and 5..
        /// </summary>
        internal static string ErrorRatingRange {
            get {
                return ResourceManager.GetString("ErrorRatingRange", resourceCulture);
            }
        }
    }
}
